# Base Ingress Template for Application
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helabooking-app-ingress
spec:
  ingressClassName: traefik # Patchable in overlays if needed
  rules:
    - host: host-placeholder # Patchable in overlays
      http:
        paths:
          # --- Backend Routes ---
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: user-service-svc
                port:
                  number: 8081
          - path: /api/events
            pathType: Prefix
            backend:
              service:
                name: event-service-svc
                port:
                  number: 8082
          - path: /api/bookings
            pathType: Prefix
            backend:
              service:
                name: booking-service-svc
                port:
                  number: 8083
          - path: /api/tickets
            pathType: Prefix
            backend:
              service:
                name: ticketing-service-svc
                port:
                  number: 8084
          - path: /api/notifications
            pathType: Prefix
            backend:
              service:
                name: notification-service-svc
                port:
                  number: 8085
          - path: /api/audits
            pathType: Prefix
            backend:
              service:
                name: audit-service-svc
                port:
                  number: 8086

          # --- Frontend Route (Must be last) ---
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80
