# Base Service Template for Database
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  clusterIP: None # Headless service for StatefulSet
  ports:
    - port: 5432
      targetPort: 5432
      name: tcp-postgres
  selector:
    app: database
