##### Patching Frontend Deployment for Helabooking app #####
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: web
          image: helabooking/frontend:latest
          env:
            - name: VITE_USER_API_BASE_URL
              value: "http://user-service-svc:8081/api/users" # Patch User Service URL
            - name: VITE_EVENT_API_BASE_URL
              value: "http://event-service-svc:8082/api/events" # Patch Event Service URL
            - name: VITE_BOOKING_API_BASE_URL
              value: "http://booking-service-svc:8083/api/bookings" # Patch Booking Service URL
            - name: VITE_TICKETING_API_BASE_URL
              value: "http://ticketing-service-svc:8084/api/tickets" # Patch Ticketing Service URL
