##### Patching Frontend Deployment for Helabooking app #####
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    # SYNC WAVE 100: ALWAYS LAST
    # This ensures Frontend waits for all backends (Waves 1-99)
    argocd.argoproj.io/sync-wave: "100"
spec:
  template:
    spec:
      containers:
        - name: web
          image: helabooking/frontend:latest
          env:
            - name: VITE_USER_API_BASE_URL
              value: "http://user-service-svc:8081/api" # Patch User Service URL
            - name: VITE_EVENT_API_BASE_URL
              value: "http://event-service-svc:8082/api" # Patch Event Service URL
            - name: VITE_BOOKING_API_BASE_URL
              value: "http://booking-service-svc:8083/api" # Patch Booking Service URL
            - name: VITE_TICKETING_API_BASE_URL
              value: "http://ticketing-service-svc:8084/api" # Patch Ticketing Service URL
